---
title: "Read Data From the Web"
author: "Lu Qiu"
date: "2023-10-12"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

Import NSDUH data
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html =
  read_html(nsduh_url)
```


```{r}
marj_use_df =
  nsduh_html |>
  html_table() |>
  first() |>
  slice(-1)
```

Import star wars ...

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html =
  read_html(swm_url)
```


```{r}
swm_title_vec =
  swm_html |>
  html_element('.lister-item-header a') |>
  html_text()

swm_gross_rev_vec =
  swm_html |> 
  html_elements(".text-muted .ghost~ .text-muted+ span") |> 
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec,
    gross_rev = swm_gross_rev_vec
  )
```


## APIs

Get water data from NYC
```{r}
nyc_water_df =
  GET('https://data.cityofnewyork.us/resource/ia2d-e54m.csv') |>
  content()
```

BRFSS Data
```{r}
brfss_df =
  GET('https://data.cdc.gov/resource/acme-vg9e.csv',
      query = list('$limit' = 5000)) |>
  content()
```


Try it now!

```{r}
poke_df =
  GET('https://pokeapi.co/api/v2/pokemon/ditto') |>
  content()
```

